server:
  port: 8011
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: 123456
    url: jdbc:mysql://localhost/mine?serverTimezone=GMT%2B8
    username: root
  redis:
    database: 0
    host: localhost
    port: 6379
    password: 123456
  thymeleaf:
    cache: false
    encoding: UTF-8
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5


mybatis:
  mapperLocations: classpath:mapper/*.xml
  typeAliasesPackage: com.swaggertest.demo
  configuration:
     map-underscore-to-camel-case: true

logging:
  level:
    com:
      swaggertest:
        demo:
          dao: DEBUG

pagehelper:
  helperDialect: mysql
  params: count=countSql
  reasonable: true
  supportMethodsArguments: true


